apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: holewinskidev
spec:
  rules:
    - host: www.next.holewinski.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: holewinskidev
                port:
                  number: 80
